### ISSUE TITLE
Feature: Add search by genre

### ISSUE THREAD

**Issue by TommasU** [fall2021-csc510-group40/filmfan#34]
- Update frontend to allow recommendations based on genre
- Update tmdb and cache methods to allow for genre as an input
- Connect repo to movie recommendations based on genre

**Comment by g-fringer** [comment]
Steps taken to complete this:
* The option for a genre has been added to the main search.
* Code has been added for the query so that this option does not need to be used, but the list returned from the query by title is pruned to only return movies that contain the target genre.

Testing for Confirmation:
* Did a manual search for the movie "Saw" without a genre and clicked search.
* Compared the above results with a search for "Saw" with the genre "Horror", and the expected movies from the Saw Franchise remained.
* Did a search for "Saw" with the genre "Comedy", and different movies were displayed (Just "I Saw Mommy Kissing Santa Claus")

Other Notes:
* The genre select area is in a position that currently makes sense, but if more features were added to refine the search, the location may need to change.
* The ability to search by genre is only on this initial search, and it may be beneficial to have an enhancement to refine results after a search on the results page (feature for next phase).
